### ISSUE TITLE
Difficult to read blue METAR text on >D page

### ISSUE THREAD

**Issue by shosk** [avare-docs/avare-docs.github.io#9]
The blue on black font color is very hard to read, especially in bright light.

I suggest either changing all the METAR text to white (or yellow) on black, or add the ability to change font colors on that page.

![Screenshot_20220912-102926 (1)](https://user-images.githubusercontent.com/69326454/189930866-a0526dae-f499-4ef6-b286-3f64b62d5b2c.jpg)

**Comment by gustafson** [comment]
Hi, I'm going to close this one.
This repo is for the website and documentation.  Issues for the app must be submitted to https://github.com/apps4av/avare.
Pete
